flasksite/twitter/forms.py
import json
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError
import yfinance as yf

class StockForm(FlaskForm):
    tickers_list =[]
    with open("stock_tickers.txt") as tickers_file:
        tickers = tickers_file.readlines()
        for ticker in tickers:
            tickers_list.append(ticker[0:len(ticker)-1])

    stock = StringField("Enter a Stock Ticker:", validators=[DataRequired()])
    submit = SubmitField("Enter")

    def validate_stock(self, stock, tickers_list=tickers_list):
        '''
        Less efficient ways of checking if ticker is valid

        with open("stocks.json") as file:
            tickers = json.load(file)
            tickers_list =[]
            for entry in tickers:
                if("ACT Symbol" in entry):
                    tickers_list.append(entry["ACT Symbol"])
                elif("Symbol" in entry):
                    tickers_list.append(entry["Symbol"])
        '''
        if(not(stock.data.upper() in tickers_list)):
            raise ValidationError(f'"{stock.data.upper()}" is not a valid NYSE or Nasdaq listed stock ticker.')
        

flasksite/__init__.py
'''
Create flask app and SQL database here
'''
from os import error
from flask import Flask, config
from flask_bootstrap import Bootstrap
from flasksite.config import Config


app = Flask(__name__)
app.config.from_object(Config)
bootstrap = Bootstrap(app)

from flasksite.twitter.routes import twitter
from flasksite.main.routes import main
from flasksite.errors.handlers import errors

app.register_blueprint(twitter)
app.register_blueprint(main)
app.register_blueprint(errors)

flasksite/main/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint

main = Blueprint("main", __name__)

@main.route("/about")
def about():
  return render_template("about.html", title="About")

flasksite/twitter/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flasksite.twitter.forms import StockForm
import yfinance as yf
from flasksite.twitter.utils import get_prices, get_sentiments_times, get_chart_url, getShortName
from quickchart import QuickChart

twitter = Blueprint("twitter", __name__)

@twitter.route("/", methods=["GET", "POST"])
@twitter.route("/twitter", methods=["GET", "POST"])
def twitter_chart():

    form = StockForm()
    chart_url = None
    flash("Upon form submission, your chart might take a few seconds to load.", "info")
    if form.validate_on_submit():
        sentiments_times = get_sentiments_times(form.stock.data)   
        prices = get_prices(sentiments_times[1], (form.stock.data))
        dates = []
        for time in sentiments_times[1]:
                dates.append(time[0:10])

        sentiments = sentiments_times[0]
        chart_url = get_chart_url(dates, prices, sentiments, form.stock.data)

    return render_template("twitter.html", form = form, chart_url = chart_url)

flasksite/templates/about.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <h1 class="article-metadata">About</h1>
        <p>
          This site, for now, compares twitter sentiment to stock performance over the past few days (all I can do for free). 
          <br><br>
          Twitter Analysis:
          <br>
          When a valid stock ticker is entered, the chart generated shows a calculated Twitter sentiment value for the stock(ranging from -1 to 1, with higher being more positive), as well as that stock's price, over the past 5 days excluding the current day. 
          <br><br>
          Reddit sentiment analysis and longer-term Twitter analysis is also in the works. 
          <br><br>
          The source code for my project can be found at my Github: rohangx0072.
        </p>
  </div>
{% endblock content%}

flasksite/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    
    {% if title %}
    <title>Twitter Sentiment Stock Analysis - {{ title }}</title>
    {% else %}
    <title>Twitter Sentiment Stock Analysis</title>
    {% endif %}

        <body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{url_for('main.about')}}">About</a>
                <a class="nav-item nav-link" href="{{url_for('twitter.twitter_chart')}}">Twitter Analysis</a>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
      </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</head>
</html>

flasksite/templates/twitter.html
{% extends "layout.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
  <div class="content-section">
    <h1 class="article-metadata">Twitter Sentiment Stock Analysis</h1>
        Enter a NYSE or Nasdaq stock ticker below to see a chart of the stock's stock price overlaid with a calculated value of Twitter sentiment (ranging form -1 to 1, with higher being more positive) about the stock over the past few days. Your chart might take a few seconds to load, so please hang tight.

      <br><br>

    <div>
      {{ wtf.quick_form(form, button_map={'submit':'info'}) }}
    </div>
  </div>

  {% if chart_url %}
  <div class="content-section fill">
    <img src="{{chart_url}}">  
  </div>
  {% endif %}
{% endblock content%}